image: docker:stable

services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay2

build:
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE
